/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PressRouteImport } from './routes/press'
import { Route as PartiesRouteImport } from './routes/parties'
import { Route as MobileRouteImport } from './routes/mobile'
import { Route as MembershipCardRouteImport } from './routes/membership-card'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MemberLoginRouteImport } from './routes/member-login'
import { Route as MemberBookRouteImport } from './routes/member-book'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookNowRouteImport } from './routes/book-now'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MemberBookingIdRouteImport } from './routes/member-booking.$id'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as StaffMemberIdRouteImport } from './routes/staff.member.$id'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTestSquareCalendarRouteImport } from './routes/api/public/test-square-calendar'
import { Route as ApiPublicSyncSquareServicesApplyRouteImport } from './routes/api/public/sync-square-services-apply'
import { Route as ApiPublicSyncSquareServicesRouteImport } from './routes/api/public/sync-square-services'
import { Route as ApiPublicSyncSquareMembershipsRouteImport } from './routes/api/public/sync-square-memberships'
import { Route as ApiPublicSyncSquareCustomersRouteImport } from './routes/api/public/sync-square-customers'
import { Route as ApiPublicSyncServicesToSquareRouteImport } from './routes/api/public/sync-services-to-square'
import { Route as ApiPublicStaffTodayRouteImport } from './routes/api/public/staff-today'
import { Route as ApiPublicStaffPinRouteImport } from './routes/api/public/staff-pin'
import { Route as ApiPublicSquareConfigRouteImport } from './routes/api/public/square-config'
import { Route as ApiPublicPullSquareVariationIdsRouteImport } from './routes/api/public/pull-square-variation-ids'
import { Route as ApiPublicPartyInquiryRouteImport } from './routes/api/public/party-inquiry'
import { Route as ApiPublicNotifySignupRouteImport } from './routes/api/public/notify-signup'
import { Route as ApiPublicNewsletterSignupRouteImport } from './routes/api/public/newsletter-signup'
import { Route as ApiPublicMembershipsUsageRouteImport } from './routes/api/public/memberships-usage'
import { Route as ApiPublicMembershipUndoRouteImport } from './routes/api/public/membership-undo'
import { Route as ApiPublicMembershipStaffRouteImport } from './routes/api/public/membership-staff'
import { Route as ApiPublicMembershipRedeemRouteImport } from './routes/api/public/membership-redeem'
import { Route as ApiPublicMembershipPhotoRouteImport } from './routes/api/public/membership-photo'
import { Route as ApiPublicMembershipEditRedemptionRouteImport } from './routes/api/public/membership-edit-redemption'
import { Route as ApiPublicMembershipCardRouteImport } from './routes/api/public/membership-card'
import { Route as ApiPublicMembershipCancelRouteImport } from './routes/api/public/membership-cancel'
import { Route as ApiPublicMemberPhoneSigninRouteImport } from './routes/api/public/member-phone-signin'
import { Route as ApiPublicMemberMagicLinkRouteImport } from './routes/api/public/member-magic-link'
import { Route as ApiPublicMemberHistoryRouteImport } from './routes/api/public/member-history'
import { Route as ApiPublicMemberBookingRouteImport } from './routes/api/public/member-booking'
import { Route as ApiPublicMemberBookRouteImport } from './routes/api/public/member-book'
import { Route as ApiPublicLoyaltyLookupRouteImport } from './routes/api/public/loyalty-lookup'
import { Route as ApiPublicEnrollMembershipRouteImport } from './routes/api/public/enroll-membership'
import { Route as ApiPublicDispatchRedemptionEmailsRouteImport } from './routes/api/public/dispatch-redemption-emails'
import { Route as ApiPublicDispatchMemberMonthlyRouteImport } from './routes/api/public/dispatch-member-monthly'
import { Route as ApiPublicDedupeSquareCustomersRouteImport } from './routes/api/public/dedupe-square-customers'
import { Route as ApiPublicDebugSquareCatalogRouteImport } from './routes/api/public/debug-square-catalog'
import { Route as ApiPublicContactSubmitRouteImport } from './routes/api/public/contact-submit'
import { Route as ApiPublicCheckMemberEligibleRouteImport } from './routes/api/public/check-member-eligible'
import { Route as ApiPublicBusySlotsRouteImport } from './routes/api/public/busy-slots'
import { Route as ApiPublicBookingSettingsRouteImport } from './routes/api/public/booking-settings'
import { Route as ApiPublicBookWithDepositRouteImport } from './routes/api/public/book-with-deposit'
import { Route as ApiPublicBookRouteImport } from './routes/api/public/book'
import { Route as ApiPublicAvailableSlotsRouteImport } from './routes/api/public/available-slots'
import { Route as ApiPublicAdminMemberSearchRouteImport } from './routes/api/public/admin-member-search'
import { Route as ApiPublicAdminBookingUpdateRouteImport } from './routes/api/public/admin-booking-update'
import { Route as ApiPublicAdminBookingDetailRouteImport } from './routes/api/public/admin-booking-detail'
import { Route as ApiPublicAdminBookingDeleteRouteImport } from './routes/api/public/admin-booking-delete'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiesRoute = PartiesRouteImport.update({
  id: '/parties',
  path: '/parties',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileRoute = MobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipCardRoute = MembershipCardRouteImport.update({
  id: '/membership-card',
  path: '/membership-card',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberLoginRoute = MemberLoginRouteImport.update({
  id: '/member-login',
  path: '/member-login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberBookRoute = MemberBookRouteImport.update({
  id: '/member-book',
  path: '/member-book',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookNowRoute = BookNowRouteImport.update({
  id: '/book-now',
  path: '/book-now',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberBookingIdRoute = MemberBookingIdRouteImport.update({
  id: '/member-booking/$id',
  path: '/member-booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffMemberIdRoute = StaffMemberIdRouteImport.update({
  id: '/member/$id',
  path: '/member/$id',
  getParentRoute: () => StaffRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestSquareCalendarRoute =
  ApiPublicTestSquareCalendarRouteImport.update({
    id: '/api/public/test-square-calendar',
    path: '/api/public/test-square-calendar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncSquareServicesApplyRoute =
  ApiPublicSyncSquareServicesApplyRouteImport.update({
    id: '/api/public/sync-square-services-apply',
    path: '/api/public/sync-square-services-apply',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncSquareServicesRoute =
  ApiPublicSyncSquareServicesRouteImport.update({
    id: '/api/public/sync-square-services',
    path: '/api/public/sync-square-services',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncSquareMembershipsRoute =
  ApiPublicSyncSquareMembershipsRouteImport.update({
    id: '/api/public/sync-square-memberships',
    path: '/api/public/sync-square-memberships',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncSquareCustomersRoute =
  ApiPublicSyncSquareCustomersRouteImport.update({
    id: '/api/public/sync-square-customers',
    path: '/api/public/sync-square-customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncServicesToSquareRoute =
  ApiPublicSyncServicesToSquareRouteImport.update({
    id: '/api/public/sync-services-to-square',
    path: '/api/public/sync-services-to-square',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStaffTodayRoute = ApiPublicStaffTodayRouteImport.update({
  id: '/api/public/staff-today',
  path: '/api/public/staff-today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStaffPinRoute = ApiPublicStaffPinRouteImport.update({
  id: '/api/public/staff-pin',
  path: '/api/public/staff-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSquareConfigRoute = ApiPublicSquareConfigRouteImport.update({
  id: '/api/public/square-config',
  path: '/api/public/square-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPullSquareVariationIdsRoute =
  ApiPublicPullSquareVariationIdsRouteImport.update({
    id: '/api/public/pull-square-variation-ids',
    path: '/api/public/pull-square-variation-ids',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPartyInquiryRoute = ApiPublicPartyInquiryRouteImport.update({
  id: '/api/public/party-inquiry',
  path: '/api/public/party-inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifySignupRoute = ApiPublicNotifySignupRouteImport.update({
  id: '/api/public/notify-signup',
  path: '/api/public/notify-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNewsletterSignupRoute =
  ApiPublicNewsletterSignupRouteImport.update({
    id: '/api/public/newsletter-signup',
    path: '/api/public/newsletter-signup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMembershipsUsageRoute =
  ApiPublicMembershipsUsageRouteImport.update({
    id: '/api/public/memberships-usage',
    path: '/api/public/memberships-usage',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMembershipUndoRoute = ApiPublicMembershipUndoRouteImport.update({
  id: '/api/public/membership-undo',
  path: '/api/public/membership-undo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMembershipStaffRoute =
  ApiPublicMembershipStaffRouteImport.update({
    id: '/api/public/membership-staff',
    path: '/api/public/membership-staff',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMembershipRedeemRoute =
  ApiPublicMembershipRedeemRouteImport.update({
    id: '/api/public/membership-redeem',
    path: '/api/public/membership-redeem',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMembershipPhotoRoute =
  ApiPublicMembershipPhotoRouteImport.update({
    id: '/api/public/membership-photo',
    path: '/api/public/membership-photo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMembershipEditRedemptionRoute =
  ApiPublicMembershipEditRedemptionRouteImport.update({
    id: '/api/public/membership-edit-redemption',
    path: '/api/public/membership-edit-redemption',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMembershipCardRoute = ApiPublicMembershipCardRouteImport.update({
  id: '/api/public/membership-card',
  path: '/api/public/membership-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMembershipCancelRoute =
  ApiPublicMembershipCancelRouteImport.update({
    id: '/api/public/membership-cancel',
    path: '/api/public/membership-cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMemberPhoneSigninRoute =
  ApiPublicMemberPhoneSigninRouteImport.update({
    id: '/api/public/member-phone-signin',
    path: '/api/public/member-phone-signin',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMemberMagicLinkRoute =
  ApiPublicMemberMagicLinkRouteImport.update({
    id: '/api/public/member-magic-link',
    path: '/api/public/member-magic-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMemberHistoryRoute = ApiPublicMemberHistoryRouteImport.update({
  id: '/api/public/member-history',
  path: '/api/public/member-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMemberBookingRoute = ApiPublicMemberBookingRouteImport.update({
  id: '/api/public/member-booking',
  path: '/api/public/member-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMemberBookRoute = ApiPublicMemberBookRouteImport.update({
  id: '/api/public/member-book',
  path: '/api/public/member-book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLoyaltyLookupRoute = ApiPublicLoyaltyLookupRouteImport.update({
  id: '/api/public/loyalty-lookup',
  path: '/api/public/loyalty-lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnrollMembershipRoute =
  ApiPublicEnrollMembershipRouteImport.update({
    id: '/api/public/enroll-membership',
    path: '/api/public/enroll-membership',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDispatchRedemptionEmailsRoute =
  ApiPublicDispatchRedemptionEmailsRouteImport.update({
    id: '/api/public/dispatch-redemption-emails',
    path: '/api/public/dispatch-redemption-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDispatchMemberMonthlyRoute =
  ApiPublicDispatchMemberMonthlyRouteImport.update({
    id: '/api/public/dispatch-member-monthly',
    path: '/api/public/dispatch-member-monthly',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDedupeSquareCustomersRoute =
  ApiPublicDedupeSquareCustomersRouteImport.update({
    id: '/api/public/dedupe-square-customers',
    path: '/api/public/dedupe-square-customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDebugSquareCatalogRoute =
  ApiPublicDebugSquareCatalogRouteImport.update({
    id: '/api/public/debug-square-catalog',
    path: '/api/public/debug-square-catalog',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContactSubmitRoute = ApiPublicContactSubmitRouteImport.update({
  id: '/api/public/contact-submit',
  path: '/api/public/contact-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckMemberEligibleRoute =
  ApiPublicCheckMemberEligibleRouteImport.update({
    id: '/api/public/check-member-eligible',
    path: '/api/public/check-member-eligible',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBusySlotsRoute = ApiPublicBusySlotsRouteImport.update({
  id: '/api/public/busy-slots',
  path: '/api/public/busy-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingSettingsRoute =
  ApiPublicBookingSettingsRouteImport.update({
    id: '/api/public/booking-settings',
    path: '/api/public/booking-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookWithDepositRoute =
  ApiPublicBookWithDepositRouteImport.update({
    id: '/api/public/book-with-deposit',
    path: '/api/public/book-with-deposit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookRoute = ApiPublicBookRouteImport.update({
  id: '/api/public/book',
  path: '/api/public/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvailableSlotsRoute = ApiPublicAvailableSlotsRouteImport.update({
  id: '/api/public/available-slots',
  path: '/api/public/available-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminMemberSearchRoute =
  ApiPublicAdminMemberSearchRouteImport.update({
    id: '/api/public/admin-member-search',
    path: '/api/public/admin-member-search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminBookingUpdateRoute =
  ApiPublicAdminBookingUpdateRouteImport.update({
    id: '/api/public/admin-booking-update',
    path: '/api/public/admin-booking-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminBookingDetailRoute =
  ApiPublicAdminBookingDetailRouteImport.update({
    id: '/api/public/admin-booking-detail',
    path: '/api/public/admin-booking-detail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminBookingDeleteRoute =
  ApiPublicAdminBookingDeleteRouteImport.update({
    id: '/api/public/admin-booking-delete',
    path: '/api/public/admin-booking-delete',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/book-now': typeof BookNowRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/member-book': typeof MemberBookRoute
  '/member-login': typeof MemberLoginRoute
  '/members': typeof MembersRoute
  '/membership': typeof MembershipRoute
  '/membership-card': typeof MembershipCardRoute
  '/mobile': typeof MobileRoute
  '/parties': typeof PartiesRoute
  '/press': typeof PressRoute
  '/programs': typeof ProgramsRoute
  '/rewards': typeof RewardsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/member-booking/$id': typeof MemberBookingIdRoute
  '/api/public/admin-booking-delete': typeof ApiPublicAdminBookingDeleteRoute
  '/api/public/admin-booking-detail': typeof ApiPublicAdminBookingDetailRoute
  '/api/public/admin-booking-update': typeof ApiPublicAdminBookingUpdateRoute
  '/api/public/admin-member-search': typeof ApiPublicAdminMemberSearchRoute
  '/api/public/available-slots': typeof ApiPublicAvailableSlotsRoute
  '/api/public/book': typeof ApiPublicBookRoute
  '/api/public/book-with-deposit': typeof ApiPublicBookWithDepositRoute
  '/api/public/booking-settings': typeof ApiPublicBookingSettingsRoute
  '/api/public/busy-slots': typeof ApiPublicBusySlotsRoute
  '/api/public/check-member-eligible': typeof ApiPublicCheckMemberEligibleRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/debug-square-catalog': typeof ApiPublicDebugSquareCatalogRoute
  '/api/public/dedupe-square-customers': typeof ApiPublicDedupeSquareCustomersRoute
  '/api/public/dispatch-member-monthly': typeof ApiPublicDispatchMemberMonthlyRoute
  '/api/public/dispatch-redemption-emails': typeof ApiPublicDispatchRedemptionEmailsRoute
  '/api/public/enroll-membership': typeof ApiPublicEnrollMembershipRoute
  '/api/public/loyalty-lookup': typeof ApiPublicLoyaltyLookupRoute
  '/api/public/member-book': typeof ApiPublicMemberBookRoute
  '/api/public/member-booking': typeof ApiPublicMemberBookingRoute
  '/api/public/member-history': typeof ApiPublicMemberHistoryRoute
  '/api/public/member-magic-link': typeof ApiPublicMemberMagicLinkRoute
  '/api/public/member-phone-signin': typeof ApiPublicMemberPhoneSigninRoute
  '/api/public/membership-cancel': typeof ApiPublicMembershipCancelRoute
  '/api/public/membership-card': typeof ApiPublicMembershipCardRoute
  '/api/public/membership-edit-redemption': typeof ApiPublicMembershipEditRedemptionRoute
  '/api/public/membership-photo': typeof ApiPublicMembershipPhotoRoute
  '/api/public/membership-redeem': typeof ApiPublicMembershipRedeemRoute
  '/api/public/membership-staff': typeof ApiPublicMembershipStaffRoute
  '/api/public/membership-undo': typeof ApiPublicMembershipUndoRoute
  '/api/public/memberships-usage': typeof ApiPublicMembershipsUsageRoute
  '/api/public/newsletter-signup': typeof ApiPublicNewsletterSignupRoute
  '/api/public/notify-signup': typeof ApiPublicNotifySignupRoute
  '/api/public/party-inquiry': typeof ApiPublicPartyInquiryRoute
  '/api/public/pull-square-variation-ids': typeof ApiPublicPullSquareVariationIdsRoute
  '/api/public/square-config': typeof ApiPublicSquareConfigRoute
  '/api/public/staff-pin': typeof ApiPublicStaffPinRoute
  '/api/public/staff-today': typeof ApiPublicStaffTodayRoute
  '/api/public/sync-services-to-square': typeof ApiPublicSyncServicesToSquareRoute
  '/api/public/sync-square-customers': typeof ApiPublicSyncSquareCustomersRoute
  '/api/public/sync-square-memberships': typeof ApiPublicSyncSquareMembershipsRoute
  '/api/public/sync-square-services': typeof ApiPublicSyncSquareServicesRoute
  '/api/public/sync-square-services-apply': typeof ApiPublicSyncSquareServicesApplyRoute
  '/api/public/test-square-calendar': typeof ApiPublicTestSquareCalendarRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/staff/member/$id': typeof StaffMemberIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/book-now': typeof BookNowRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/member-book': typeof MemberBookRoute
  '/member-login': typeof MemberLoginRoute
  '/members': typeof MembersRoute
  '/membership': typeof MembershipRoute
  '/membership-card': typeof MembershipCardRoute
  '/mobile': typeof MobileRoute
  '/parties': typeof PartiesRoute
  '/press': typeof PressRoute
  '/programs': typeof ProgramsRoute
  '/rewards': typeof RewardsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/member-booking/$id': typeof MemberBookingIdRoute
  '/api/public/admin-booking-delete': typeof ApiPublicAdminBookingDeleteRoute
  '/api/public/admin-booking-detail': typeof ApiPublicAdminBookingDetailRoute
  '/api/public/admin-booking-update': typeof ApiPublicAdminBookingUpdateRoute
  '/api/public/admin-member-search': typeof ApiPublicAdminMemberSearchRoute
  '/api/public/available-slots': typeof ApiPublicAvailableSlotsRoute
  '/api/public/book': typeof ApiPublicBookRoute
  '/api/public/book-with-deposit': typeof ApiPublicBookWithDepositRoute
  '/api/public/booking-settings': typeof ApiPublicBookingSettingsRoute
  '/api/public/busy-slots': typeof ApiPublicBusySlotsRoute
  '/api/public/check-member-eligible': typeof ApiPublicCheckMemberEligibleRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/debug-square-catalog': typeof ApiPublicDebugSquareCatalogRoute
  '/api/public/dedupe-square-customers': typeof ApiPublicDedupeSquareCustomersRoute
  '/api/public/dispatch-member-monthly': typeof ApiPublicDispatchMemberMonthlyRoute
  '/api/public/dispatch-redemption-emails': typeof ApiPublicDispatchRedemptionEmailsRoute
  '/api/public/enroll-membership': typeof ApiPublicEnrollMembershipRoute
  '/api/public/loyalty-lookup': typeof ApiPublicLoyaltyLookupRoute
  '/api/public/member-book': typeof ApiPublicMemberBookRoute
  '/api/public/member-booking': typeof ApiPublicMemberBookingRoute
  '/api/public/member-history': typeof ApiPublicMemberHistoryRoute
  '/api/public/member-magic-link': typeof ApiPublicMemberMagicLinkRoute
  '/api/public/member-phone-signin': typeof ApiPublicMemberPhoneSigninRoute
  '/api/public/membership-cancel': typeof ApiPublicMembershipCancelRoute
  '/api/public/membership-card': typeof ApiPublicMembershipCardRoute
  '/api/public/membership-edit-redemption': typeof ApiPublicMembershipEditRedemptionRoute
  '/api/public/membership-photo': typeof ApiPublicMembershipPhotoRoute
  '/api/public/membership-redeem': typeof ApiPublicMembershipRedeemRoute
  '/api/public/membership-staff': typeof ApiPublicMembershipStaffRoute
  '/api/public/membership-undo': typeof ApiPublicMembershipUndoRoute
  '/api/public/memberships-usage': typeof ApiPublicMembershipsUsageRoute
  '/api/public/newsletter-signup': typeof ApiPublicNewsletterSignupRoute
  '/api/public/notify-signup': typeof ApiPublicNotifySignupRoute
  '/api/public/party-inquiry': typeof ApiPublicPartyInquiryRoute
  '/api/public/pull-square-variation-ids': typeof ApiPublicPullSquareVariationIdsRoute
  '/api/public/square-config': typeof ApiPublicSquareConfigRoute
  '/api/public/staff-pin': typeof ApiPublicStaffPinRoute
  '/api/public/staff-today': typeof ApiPublicStaffTodayRoute
  '/api/public/sync-services-to-square': typeof ApiPublicSyncServicesToSquareRoute
  '/api/public/sync-square-customers': typeof ApiPublicSyncSquareCustomersRoute
  '/api/public/sync-square-memberships': typeof ApiPublicSyncSquareMembershipsRoute
  '/api/public/sync-square-services': typeof ApiPublicSyncSquareServicesRoute
  '/api/public/sync-square-services-apply': typeof ApiPublicSyncSquareServicesApplyRoute
  '/api/public/test-square-calendar': typeof ApiPublicTestSquareCalendarRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/staff/member/$id': typeof StaffMemberIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/book-now': typeof BookNowRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/member-book': typeof MemberBookRoute
  '/member-login': typeof MemberLoginRoute
  '/members': typeof MembersRoute
  '/membership': typeof MembershipRoute
  '/membership-card': typeof MembershipCardRoute
  '/mobile': typeof MobileRoute
  '/parties': typeof PartiesRoute
  '/press': typeof PressRoute
  '/programs': typeof ProgramsRoute
  '/rewards': typeof RewardsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff': typeof StaffRouteWithChildren
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/member-booking/$id': typeof MemberBookingIdRoute
  '/api/public/admin-booking-delete': typeof ApiPublicAdminBookingDeleteRoute
  '/api/public/admin-booking-detail': typeof ApiPublicAdminBookingDetailRoute
  '/api/public/admin-booking-update': typeof ApiPublicAdminBookingUpdateRoute
  '/api/public/admin-member-search': typeof ApiPublicAdminMemberSearchRoute
  '/api/public/available-slots': typeof ApiPublicAvailableSlotsRoute
  '/api/public/book': typeof ApiPublicBookRoute
  '/api/public/book-with-deposit': typeof ApiPublicBookWithDepositRoute
  '/api/public/booking-settings': typeof ApiPublicBookingSettingsRoute
  '/api/public/busy-slots': typeof ApiPublicBusySlotsRoute
  '/api/public/check-member-eligible': typeof ApiPublicCheckMemberEligibleRoute
  '/api/public/contact-submit': typeof ApiPublicContactSubmitRoute
  '/api/public/debug-square-catalog': typeof ApiPublicDebugSquareCatalogRoute
  '/api/public/dedupe-square-customers': typeof ApiPublicDedupeSquareCustomersRoute
  '/api/public/dispatch-member-monthly': typeof ApiPublicDispatchMemberMonthlyRoute
  '/api/public/dispatch-redemption-emails': typeof ApiPublicDispatchRedemptionEmailsRoute
  '/api/public/enroll-membership': typeof ApiPublicEnrollMembershipRoute
  '/api/public/loyalty-lookup': typeof ApiPublicLoyaltyLookupRoute
  '/api/public/member-book': typeof ApiPublicMemberBookRoute
  '/api/public/member-booking': typeof ApiPublicMemberBookingRoute
  '/api/public/member-history': typeof ApiPublicMemberHistoryRoute
  '/api/public/member-magic-link': typeof ApiPublicMemberMagicLinkRoute
  '/api/public/member-phone-signin': typeof ApiPublicMemberPhoneSigninRoute
  '/api/public/membership-cancel': typeof ApiPublicMembershipCancelRoute
  '/api/public/membership-card': typeof ApiPublicMembershipCardRoute
  '/api/public/membership-edit-redemption': typeof ApiPublicMembershipEditRedemptionRoute
  '/api/public/membership-photo': typeof ApiPublicMembershipPhotoRoute
  '/api/public/membership-redeem': typeof ApiPublicMembershipRedeemRoute
  '/api/public/membership-staff': typeof ApiPublicMembershipStaffRoute
  '/api/public/membership-undo': typeof ApiPublicMembershipUndoRoute
  '/api/public/memberships-usage': typeof ApiPublicMembershipsUsageRoute
  '/api/public/newsletter-signup': typeof ApiPublicNewsletterSignupRoute
  '/api/public/notify-signup': typeof ApiPublicNotifySignupRoute
  '/api/public/party-inquiry': typeof ApiPublicPartyInquiryRoute
  '/api/public/pull-square-variation-ids': typeof ApiPublicPullSquareVariationIdsRoute
  '/api/public/square-config': typeof ApiPublicSquareConfigRoute
  '/api/public/staff-pin': typeof ApiPublicStaffPinRoute
  '/api/public/staff-today': typeof ApiPublicStaffTodayRoute
  '/api/public/sync-services-to-square': typeof ApiPublicSyncServicesToSquareRoute
  '/api/public/sync-square-customers': typeof ApiPublicSyncSquareCustomersRoute
  '/api/public/sync-square-memberships': typeof ApiPublicSyncSquareMembershipsRoute
  '/api/public/sync-square-services': typeof ApiPublicSyncSquareServicesRoute
  '/api/public/sync-square-services-apply': typeof ApiPublicSyncSquareServicesApplyRoute
  '/api/public/test-square-calendar': typeof ApiPublicTestSquareCalendarRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/staff/member/$id': typeof StaffMemberIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/book-now'
    | '/contact'
    | '/gallery'
    | '/member-book'
    | '/member-login'
    | '/members'
    | '/membership'
    | '/membership-card'
    | '/mobile'
    | '/parties'
    | '/press'
    | '/programs'
    | '/rewards'
    | '/services'
    | '/sitemap.xml'
    | '/staff'
    | '/email/unsubscribe'
    | '/member-booking/$id'
    | '/api/public/admin-booking-delete'
    | '/api/public/admin-booking-detail'
    | '/api/public/admin-booking-update'
    | '/api/public/admin-member-search'
    | '/api/public/available-slots'
    | '/api/public/book'
    | '/api/public/book-with-deposit'
    | '/api/public/booking-settings'
    | '/api/public/busy-slots'
    | '/api/public/check-member-eligible'
    | '/api/public/contact-submit'
    | '/api/public/debug-square-catalog'
    | '/api/public/dedupe-square-customers'
    | '/api/public/dispatch-member-monthly'
    | '/api/public/dispatch-redemption-emails'
    | '/api/public/enroll-membership'
    | '/api/public/loyalty-lookup'
    | '/api/public/member-book'
    | '/api/public/member-booking'
    | '/api/public/member-history'
    | '/api/public/member-magic-link'
    | '/api/public/member-phone-signin'
    | '/api/public/membership-cancel'
    | '/api/public/membership-card'
    | '/api/public/membership-edit-redemption'
    | '/api/public/membership-photo'
    | '/api/public/membership-redeem'
    | '/api/public/membership-staff'
    | '/api/public/membership-undo'
    | '/api/public/memberships-usage'
    | '/api/public/newsletter-signup'
    | '/api/public/notify-signup'
    | '/api/public/party-inquiry'
    | '/api/public/pull-square-variation-ids'
    | '/api/public/square-config'
    | '/api/public/staff-pin'
    | '/api/public/staff-today'
    | '/api/public/sync-services-to-square'
    | '/api/public/sync-square-customers'
    | '/api/public/sync-square-memberships'
    | '/api/public/sync-square-services'
    | '/api/public/sync-square-services-apply'
    | '/api/public/test-square-calendar'
    | '/lovable/email/suppression'
    | '/staff/member/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/book-now'
    | '/contact'
    | '/gallery'
    | '/member-book'
    | '/member-login'
    | '/members'
    | '/membership'
    | '/membership-card'
    | '/mobile'
    | '/parties'
    | '/press'
    | '/programs'
    | '/rewards'
    | '/services'
    | '/sitemap.xml'
    | '/staff'
    | '/email/unsubscribe'
    | '/member-booking/$id'
    | '/api/public/admin-booking-delete'
    | '/api/public/admin-booking-detail'
    | '/api/public/admin-booking-update'
    | '/api/public/admin-member-search'
    | '/api/public/available-slots'
    | '/api/public/book'
    | '/api/public/book-with-deposit'
    | '/api/public/booking-settings'
    | '/api/public/busy-slots'
    | '/api/public/check-member-eligible'
    | '/api/public/contact-submit'
    | '/api/public/debug-square-catalog'
    | '/api/public/dedupe-square-customers'
    | '/api/public/dispatch-member-monthly'
    | '/api/public/dispatch-redemption-emails'
    | '/api/public/enroll-membership'
    | '/api/public/loyalty-lookup'
    | '/api/public/member-book'
    | '/api/public/member-booking'
    | '/api/public/member-history'
    | '/api/public/member-magic-link'
    | '/api/public/member-phone-signin'
    | '/api/public/membership-cancel'
    | '/api/public/membership-card'
    | '/api/public/membership-edit-redemption'
    | '/api/public/membership-photo'
    | '/api/public/membership-redeem'
    | '/api/public/membership-staff'
    | '/api/public/membership-undo'
    | '/api/public/memberships-usage'
    | '/api/public/newsletter-signup'
    | '/api/public/notify-signup'
    | '/api/public/party-inquiry'
    | '/api/public/pull-square-variation-ids'
    | '/api/public/square-config'
    | '/api/public/staff-pin'
    | '/api/public/staff-today'
    | '/api/public/sync-services-to-square'
    | '/api/public/sync-square-customers'
    | '/api/public/sync-square-memberships'
    | '/api/public/sync-square-services'
    | '/api/public/sync-square-services-apply'
    | '/api/public/test-square-calendar'
    | '/lovable/email/suppression'
    | '/staff/member/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/book-now'
    | '/contact'
    | '/gallery'
    | '/member-book'
    | '/member-login'
    | '/members'
    | '/membership'
    | '/membership-card'
    | '/mobile'
    | '/parties'
    | '/press'
    | '/programs'
    | '/rewards'
    | '/services'
    | '/sitemap.xml'
    | '/staff'
    | '/email/unsubscribe'
    | '/member-booking/$id'
    | '/api/public/admin-booking-delete'
    | '/api/public/admin-booking-detail'
    | '/api/public/admin-booking-update'
    | '/api/public/admin-member-search'
    | '/api/public/available-slots'
    | '/api/public/book'
    | '/api/public/book-with-deposit'
    | '/api/public/booking-settings'
    | '/api/public/busy-slots'
    | '/api/public/check-member-eligible'
    | '/api/public/contact-submit'
    | '/api/public/debug-square-catalog'
    | '/api/public/dedupe-square-customers'
    | '/api/public/dispatch-member-monthly'
    | '/api/public/dispatch-redemption-emails'
    | '/api/public/enroll-membership'
    | '/api/public/loyalty-lookup'
    | '/api/public/member-book'
    | '/api/public/member-booking'
    | '/api/public/member-history'
    | '/api/public/member-magic-link'
    | '/api/public/member-phone-signin'
    | '/api/public/membership-cancel'
    | '/api/public/membership-card'
    | '/api/public/membership-edit-redemption'
    | '/api/public/membership-photo'
    | '/api/public/membership-redeem'
    | '/api/public/membership-staff'
    | '/api/public/membership-undo'
    | '/api/public/memberships-usage'
    | '/api/public/newsletter-signup'
    | '/api/public/notify-signup'
    | '/api/public/party-inquiry'
    | '/api/public/pull-square-variation-ids'
    | '/api/public/square-config'
    | '/api/public/staff-pin'
    | '/api/public/staff-today'
    | '/api/public/sync-services-to-square'
    | '/api/public/sync-square-customers'
    | '/api/public/sync-square-memberships'
    | '/api/public/sync-square-services'
    | '/api/public/sync-square-services-apply'
    | '/api/public/test-square-calendar'
    | '/lovable/email/suppression'
    | '/staff/member/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BookNowRoute: typeof BookNowRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  MemberBookRoute: typeof MemberBookRoute
  MemberLoginRoute: typeof MemberLoginRoute
  MembersRoute: typeof MembersRoute
  MembershipRoute: typeof MembershipRoute
  MembershipCardRoute: typeof MembershipCardRoute
  MobileRoute: typeof MobileRoute
  PartiesRoute: typeof PartiesRoute
  PressRoute: typeof PressRoute
  ProgramsRoute: typeof ProgramsRoute
  RewardsRoute: typeof RewardsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffRoute: typeof StaffRouteWithChildren
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  MemberBookingIdRoute: typeof MemberBookingIdRoute
  ApiPublicAdminBookingDeleteRoute: typeof ApiPublicAdminBookingDeleteRoute
  ApiPublicAdminBookingDetailRoute: typeof ApiPublicAdminBookingDetailRoute
  ApiPublicAdminBookingUpdateRoute: typeof ApiPublicAdminBookingUpdateRoute
  ApiPublicAdminMemberSearchRoute: typeof ApiPublicAdminMemberSearchRoute
  ApiPublicAvailableSlotsRoute: typeof ApiPublicAvailableSlotsRoute
  ApiPublicBookRoute: typeof ApiPublicBookRoute
  ApiPublicBookWithDepositRoute: typeof ApiPublicBookWithDepositRoute
  ApiPublicBookingSettingsRoute: typeof ApiPublicBookingSettingsRoute
  ApiPublicBusySlotsRoute: typeof ApiPublicBusySlotsRoute
  ApiPublicCheckMemberEligibleRoute: typeof ApiPublicCheckMemberEligibleRoute
  ApiPublicContactSubmitRoute: typeof ApiPublicContactSubmitRoute
  ApiPublicDebugSquareCatalogRoute: typeof ApiPublicDebugSquareCatalogRoute
  ApiPublicDedupeSquareCustomersRoute: typeof ApiPublicDedupeSquareCustomersRoute
  ApiPublicDispatchMemberMonthlyRoute: typeof ApiPublicDispatchMemberMonthlyRoute
  ApiPublicDispatchRedemptionEmailsRoute: typeof ApiPublicDispatchRedemptionEmailsRoute
  ApiPublicEnrollMembershipRoute: typeof ApiPublicEnrollMembershipRoute
  ApiPublicLoyaltyLookupRoute: typeof ApiPublicLoyaltyLookupRoute
  ApiPublicMemberBookRoute: typeof ApiPublicMemberBookRoute
  ApiPublicMemberBookingRoute: typeof ApiPublicMemberBookingRoute
  ApiPublicMemberHistoryRoute: typeof ApiPublicMemberHistoryRoute
  ApiPublicMemberMagicLinkRoute: typeof ApiPublicMemberMagicLinkRoute
  ApiPublicMemberPhoneSigninRoute: typeof ApiPublicMemberPhoneSigninRoute
  ApiPublicMembershipCancelRoute: typeof ApiPublicMembershipCancelRoute
  ApiPublicMembershipCardRoute: typeof ApiPublicMembershipCardRoute
  ApiPublicMembershipEditRedemptionRoute: typeof ApiPublicMembershipEditRedemptionRoute
  ApiPublicMembershipPhotoRoute: typeof ApiPublicMembershipPhotoRoute
  ApiPublicMembershipRedeemRoute: typeof ApiPublicMembershipRedeemRoute
  ApiPublicMembershipStaffRoute: typeof ApiPublicMembershipStaffRoute
  ApiPublicMembershipUndoRoute: typeof ApiPublicMembershipUndoRoute
  ApiPublicMembershipsUsageRoute: typeof ApiPublicMembershipsUsageRoute
  ApiPublicNewsletterSignupRoute: typeof ApiPublicNewsletterSignupRoute
  ApiPublicNotifySignupRoute: typeof ApiPublicNotifySignupRoute
  ApiPublicPartyInquiryRoute: typeof ApiPublicPartyInquiryRoute
  ApiPublicPullSquareVariationIdsRoute: typeof ApiPublicPullSquareVariationIdsRoute
  ApiPublicSquareConfigRoute: typeof ApiPublicSquareConfigRoute
  ApiPublicStaffPinRoute: typeof ApiPublicStaffPinRoute
  ApiPublicStaffTodayRoute: typeof ApiPublicStaffTodayRoute
  ApiPublicSyncServicesToSquareRoute: typeof ApiPublicSyncServicesToSquareRoute
  ApiPublicSyncSquareCustomersRoute: typeof ApiPublicSyncSquareCustomersRoute
  ApiPublicSyncSquareMembershipsRoute: typeof ApiPublicSyncSquareMembershipsRoute
  ApiPublicSyncSquareServicesRoute: typeof ApiPublicSyncSquareServicesRoute
  ApiPublicSyncSquareServicesApplyRoute: typeof ApiPublicSyncSquareServicesApplyRoute
  ApiPublicTestSquareCalendarRoute: typeof ApiPublicTestSquareCalendarRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parties': {
      id: '/parties'
      path: '/parties'
      fullPath: '/parties'
      preLoaderRoute: typeof PartiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile': {
      id: '/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof MobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership-card': {
      id: '/membership-card'
      path: '/membership-card'
      fullPath: '/membership-card'
      preLoaderRoute: typeof MembershipCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-login': {
      id: '/member-login'
      path: '/member-login'
      fullPath: '/member-login'
      preLoaderRoute: typeof MemberLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-book': {
      id: '/member-book'
      path: '/member-book'
      fullPath: '/member-book'
      preLoaderRoute: typeof MemberBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-now': {
      id: '/book-now'
      path: '/book-now'
      fullPath: '/book-now'
      preLoaderRoute: typeof BookNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-booking/$id': {
      id: '/member-booking/$id'
      path: '/member-booking/$id'
      fullPath: '/member-booking/$id'
      preLoaderRoute: typeof MemberBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/member/$id': {
      id: '/staff/member/$id'
      path: '/member/$id'
      fullPath: '/staff/member/$id'
      preLoaderRoute: typeof StaffMemberIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-square-calendar': {
      id: '/api/public/test-square-calendar'
      path: '/api/public/test-square-calendar'
      fullPath: '/api/public/test-square-calendar'
      preLoaderRoute: typeof ApiPublicTestSquareCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-square-services-apply': {
      id: '/api/public/sync-square-services-apply'
      path: '/api/public/sync-square-services-apply'
      fullPath: '/api/public/sync-square-services-apply'
      preLoaderRoute: typeof ApiPublicSyncSquareServicesApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-square-services': {
      id: '/api/public/sync-square-services'
      path: '/api/public/sync-square-services'
      fullPath: '/api/public/sync-square-services'
      preLoaderRoute: typeof ApiPublicSyncSquareServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-square-memberships': {
      id: '/api/public/sync-square-memberships'
      path: '/api/public/sync-square-memberships'
      fullPath: '/api/public/sync-square-memberships'
      preLoaderRoute: typeof ApiPublicSyncSquareMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-square-customers': {
      id: '/api/public/sync-square-customers'
      path: '/api/public/sync-square-customers'
      fullPath: '/api/public/sync-square-customers'
      preLoaderRoute: typeof ApiPublicSyncSquareCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-services-to-square': {
      id: '/api/public/sync-services-to-square'
      path: '/api/public/sync-services-to-square'
      fullPath: '/api/public/sync-services-to-square'
      preLoaderRoute: typeof ApiPublicSyncServicesToSquareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/staff-today': {
      id: '/api/public/staff-today'
      path: '/api/public/staff-today'
      fullPath: '/api/public/staff-today'
      preLoaderRoute: typeof ApiPublicStaffTodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/staff-pin': {
      id: '/api/public/staff-pin'
      path: '/api/public/staff-pin'
      fullPath: '/api/public/staff-pin'
      preLoaderRoute: typeof ApiPublicStaffPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/square-config': {
      id: '/api/public/square-config'
      path: '/api/public/square-config'
      fullPath: '/api/public/square-config'
      preLoaderRoute: typeof ApiPublicSquareConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pull-square-variation-ids': {
      id: '/api/public/pull-square-variation-ids'
      path: '/api/public/pull-square-variation-ids'
      fullPath: '/api/public/pull-square-variation-ids'
      preLoaderRoute: typeof ApiPublicPullSquareVariationIdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/party-inquiry': {
      id: '/api/public/party-inquiry'
      path: '/api/public/party-inquiry'
      fullPath: '/api/public/party-inquiry'
      preLoaderRoute: typeof ApiPublicPartyInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-signup': {
      id: '/api/public/notify-signup'
      path: '/api/public/notify-signup'
      fullPath: '/api/public/notify-signup'
      preLoaderRoute: typeof ApiPublicNotifySignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter-signup': {
      id: '/api/public/newsletter-signup'
      path: '/api/public/newsletter-signup'
      fullPath: '/api/public/newsletter-signup'
      preLoaderRoute: typeof ApiPublicNewsletterSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/memberships-usage': {
      id: '/api/public/memberships-usage'
      path: '/api/public/memberships-usage'
      fullPath: '/api/public/memberships-usage'
      preLoaderRoute: typeof ApiPublicMembershipsUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership-undo': {
      id: '/api/public/membership-undo'
      path: '/api/public/membership-undo'
      fullPath: '/api/public/membership-undo'
      preLoaderRoute: typeof ApiPublicMembershipUndoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership-staff': {
      id: '/api/public/membership-staff'
      path: '/api/public/membership-staff'
      fullPath: '/api/public/membership-staff'
      preLoaderRoute: typeof ApiPublicMembershipStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership-redeem': {
      id: '/api/public/membership-redeem'
      path: '/api/public/membership-redeem'
      fullPath: '/api/public/membership-redeem'
      preLoaderRoute: typeof ApiPublicMembershipRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership-photo': {
      id: '/api/public/membership-photo'
      path: '/api/public/membership-photo'
      fullPath: '/api/public/membership-photo'
      preLoaderRoute: typeof ApiPublicMembershipPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership-edit-redemption': {
      id: '/api/public/membership-edit-redemption'
      path: '/api/public/membership-edit-redemption'
      fullPath: '/api/public/membership-edit-redemption'
      preLoaderRoute: typeof ApiPublicMembershipEditRedemptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership-card': {
      id: '/api/public/membership-card'
      path: '/api/public/membership-card'
      fullPath: '/api/public/membership-card'
      preLoaderRoute: typeof ApiPublicMembershipCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership-cancel': {
      id: '/api/public/membership-cancel'
      path: '/api/public/membership-cancel'
      fullPath: '/api/public/membership-cancel'
      preLoaderRoute: typeof ApiPublicMembershipCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/member-phone-signin': {
      id: '/api/public/member-phone-signin'
      path: '/api/public/member-phone-signin'
      fullPath: '/api/public/member-phone-signin'
      preLoaderRoute: typeof ApiPublicMemberPhoneSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/member-magic-link': {
      id: '/api/public/member-magic-link'
      path: '/api/public/member-magic-link'
      fullPath: '/api/public/member-magic-link'
      preLoaderRoute: typeof ApiPublicMemberMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/member-history': {
      id: '/api/public/member-history'
      path: '/api/public/member-history'
      fullPath: '/api/public/member-history'
      preLoaderRoute: typeof ApiPublicMemberHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/member-booking': {
      id: '/api/public/member-booking'
      path: '/api/public/member-booking'
      fullPath: '/api/public/member-booking'
      preLoaderRoute: typeof ApiPublicMemberBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/member-book': {
      id: '/api/public/member-book'
      path: '/api/public/member-book'
      fullPath: '/api/public/member-book'
      preLoaderRoute: typeof ApiPublicMemberBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/loyalty-lookup': {
      id: '/api/public/loyalty-lookup'
      path: '/api/public/loyalty-lookup'
      fullPath: '/api/public/loyalty-lookup'
      preLoaderRoute: typeof ApiPublicLoyaltyLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/enroll-membership': {
      id: '/api/public/enroll-membership'
      path: '/api/public/enroll-membership'
      fullPath: '/api/public/enroll-membership'
      preLoaderRoute: typeof ApiPublicEnrollMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dispatch-redemption-emails': {
      id: '/api/public/dispatch-redemption-emails'
      path: '/api/public/dispatch-redemption-emails'
      fullPath: '/api/public/dispatch-redemption-emails'
      preLoaderRoute: typeof ApiPublicDispatchRedemptionEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dispatch-member-monthly': {
      id: '/api/public/dispatch-member-monthly'
      path: '/api/public/dispatch-member-monthly'
      fullPath: '/api/public/dispatch-member-monthly'
      preLoaderRoute: typeof ApiPublicDispatchMemberMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dedupe-square-customers': {
      id: '/api/public/dedupe-square-customers'
      path: '/api/public/dedupe-square-customers'
      fullPath: '/api/public/dedupe-square-customers'
      preLoaderRoute: typeof ApiPublicDedupeSquareCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/debug-square-catalog': {
      id: '/api/public/debug-square-catalog'
      path: '/api/public/debug-square-catalog'
      fullPath: '/api/public/debug-square-catalog'
      preLoaderRoute: typeof ApiPublicDebugSquareCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact-submit': {
      id: '/api/public/contact-submit'
      path: '/api/public/contact-submit'
      fullPath: '/api/public/contact-submit'
      preLoaderRoute: typeof ApiPublicContactSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/check-member-eligible': {
      id: '/api/public/check-member-eligible'
      path: '/api/public/check-member-eligible'
      fullPath: '/api/public/check-member-eligible'
      preLoaderRoute: typeof ApiPublicCheckMemberEligibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/busy-slots': {
      id: '/api/public/busy-slots'
      path: '/api/public/busy-slots'
      fullPath: '/api/public/busy-slots'
      preLoaderRoute: typeof ApiPublicBusySlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking-settings': {
      id: '/api/public/booking-settings'
      path: '/api/public/booking-settings'
      fullPath: '/api/public/booking-settings'
      preLoaderRoute: typeof ApiPublicBookingSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/book-with-deposit': {
      id: '/api/public/book-with-deposit'
      path: '/api/public/book-with-deposit'
      fullPath: '/api/public/book-with-deposit'
      preLoaderRoute: typeof ApiPublicBookWithDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/book': {
      id: '/api/public/book'
      path: '/api/public/book'
      fullPath: '/api/public/book'
      preLoaderRoute: typeof ApiPublicBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/available-slots': {
      id: '/api/public/available-slots'
      path: '/api/public/available-slots'
      fullPath: '/api/public/available-slots'
      preLoaderRoute: typeof ApiPublicAvailableSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-member-search': {
      id: '/api/public/admin-member-search'
      path: '/api/public/admin-member-search'
      fullPath: '/api/public/admin-member-search'
      preLoaderRoute: typeof ApiPublicAdminMemberSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-booking-update': {
      id: '/api/public/admin-booking-update'
      path: '/api/public/admin-booking-update'
      fullPath: '/api/public/admin-booking-update'
      preLoaderRoute: typeof ApiPublicAdminBookingUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-booking-detail': {
      id: '/api/public/admin-booking-detail'
      path: '/api/public/admin-booking-detail'
      fullPath: '/api/public/admin-booking-detail'
      preLoaderRoute: typeof ApiPublicAdminBookingDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin-booking-delete': {
      id: '/api/public/admin-booking-delete'
      path: '/api/public/admin-booking-delete'
      fullPath: '/api/public/admin-booking-delete'
      preLoaderRoute: typeof ApiPublicAdminBookingDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StaffRouteChildren {
  StaffMemberIdRoute: typeof StaffMemberIdRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffMemberIdRoute: StaffMemberIdRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BookNowRoute: BookNowRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  MemberBookRoute: MemberBookRoute,
  MemberLoginRoute: MemberLoginRoute,
  MembersRoute: MembersRoute,
  MembershipRoute: MembershipRoute,
  MembershipCardRoute: MembershipCardRoute,
  MobileRoute: MobileRoute,
  PartiesRoute: PartiesRoute,
  PressRoute: PressRoute,
  ProgramsRoute: ProgramsRoute,
  RewardsRoute: RewardsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffRoute: StaffRouteWithChildren,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  MemberBookingIdRoute: MemberBookingIdRoute,
  ApiPublicAdminBookingDeleteRoute: ApiPublicAdminBookingDeleteRoute,
  ApiPublicAdminBookingDetailRoute: ApiPublicAdminBookingDetailRoute,
  ApiPublicAdminBookingUpdateRoute: ApiPublicAdminBookingUpdateRoute,
  ApiPublicAdminMemberSearchRoute: ApiPublicAdminMemberSearchRoute,
  ApiPublicAvailableSlotsRoute: ApiPublicAvailableSlotsRoute,
  ApiPublicBookRoute: ApiPublicBookRoute,
  ApiPublicBookWithDepositRoute: ApiPublicBookWithDepositRoute,
  ApiPublicBookingSettingsRoute: ApiPublicBookingSettingsRoute,
  ApiPublicBusySlotsRoute: ApiPublicBusySlotsRoute,
  ApiPublicCheckMemberEligibleRoute: ApiPublicCheckMemberEligibleRoute,
  ApiPublicContactSubmitRoute: ApiPublicContactSubmitRoute,
  ApiPublicDebugSquareCatalogRoute: ApiPublicDebugSquareCatalogRoute,
  ApiPublicDedupeSquareCustomersRoute: ApiPublicDedupeSquareCustomersRoute,
  ApiPublicDispatchMemberMonthlyRoute: ApiPublicDispatchMemberMonthlyRoute,
  ApiPublicDispatchRedemptionEmailsRoute:
    ApiPublicDispatchRedemptionEmailsRoute,
  ApiPublicEnrollMembershipRoute: ApiPublicEnrollMembershipRoute,
  ApiPublicLoyaltyLookupRoute: ApiPublicLoyaltyLookupRoute,
  ApiPublicMemberBookRoute: ApiPublicMemberBookRoute,
  ApiPublicMemberBookingRoute: ApiPublicMemberBookingRoute,
  ApiPublicMemberHistoryRoute: ApiPublicMemberHistoryRoute,
  ApiPublicMemberMagicLinkRoute: ApiPublicMemberMagicLinkRoute,
  ApiPublicMemberPhoneSigninRoute: ApiPublicMemberPhoneSigninRoute,
  ApiPublicMembershipCancelRoute: ApiPublicMembershipCancelRoute,
  ApiPublicMembershipCardRoute: ApiPublicMembershipCardRoute,
  ApiPublicMembershipEditRedemptionRoute:
    ApiPublicMembershipEditRedemptionRoute,
  ApiPublicMembershipPhotoRoute: ApiPublicMembershipPhotoRoute,
  ApiPublicMembershipRedeemRoute: ApiPublicMembershipRedeemRoute,
  ApiPublicMembershipStaffRoute: ApiPublicMembershipStaffRoute,
  ApiPublicMembershipUndoRoute: ApiPublicMembershipUndoRoute,
  ApiPublicMembershipsUsageRoute: ApiPublicMembershipsUsageRoute,
  ApiPublicNewsletterSignupRoute: ApiPublicNewsletterSignupRoute,
  ApiPublicNotifySignupRoute: ApiPublicNotifySignupRoute,
  ApiPublicPartyInquiryRoute: ApiPublicPartyInquiryRoute,
  ApiPublicPullSquareVariationIdsRoute: ApiPublicPullSquareVariationIdsRoute,
  ApiPublicSquareConfigRoute: ApiPublicSquareConfigRoute,
  ApiPublicStaffPinRoute: ApiPublicStaffPinRoute,
  ApiPublicStaffTodayRoute: ApiPublicStaffTodayRoute,
  ApiPublicSyncServicesToSquareRoute: ApiPublicSyncServicesToSquareRoute,
  ApiPublicSyncSquareCustomersRoute: ApiPublicSyncSquareCustomersRoute,
  ApiPublicSyncSquareMembershipsRoute: ApiPublicSyncSquareMembershipsRoute,
  ApiPublicSyncSquareServicesRoute: ApiPublicSyncSquareServicesRoute,
  ApiPublicSyncSquareServicesApplyRoute: ApiPublicSyncSquareServicesApplyRoute,
  ApiPublicTestSquareCalendarRoute: ApiPublicTestSquareCalendarRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
